package tf

import (
	"fmt"
	"io"
	"os"

	"github.com/jgruberf5/bnkctl/internal/config"
)

// WriteTFVars renders the workspace config into terraform.tfvars at path.
// Excludes the API key, which is passed via TF_VAR_ibmcloud_api_key env
// var when terraform is invoked. kubeconfigDir is the path the IBM
// provider's ibm_container_cluster_config data sources will write into;
// requires TF v0.6.8+ to be a root-level variable.
func WriteTFVars(path string, ws *config.Workspace, kubeconfigDir string) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("creating %s: %w", path, err)
	}
	defer f.Close()
	return RenderTFVars(f, ws, kubeconfigDir)
}

// RenderTFVars writes the tfvars body to w. Exposed for tests / callers
// that want to inspect the rendering before committing it to disk.
//
// Only fields the user has explicitly set in config.yaml are emitted —
// the rest fall through to the upstream TF module's own defaults.
//
// kubeconfigDir is rendered when non-empty. Requires the upstream TF
// to declare a root-level kubeconfig_dir variable (v0.6.8+); older
// versions warn but tolerate the undeclared value.
//
// IMPORTANT: api_key is NEVER written. Pass it via the
// TF_VAR_ibmcloud_api_key env var on the terraform invocation.
func RenderTFVars(w io.Writer, ws *config.Workspace, kubeconfigDir string) error {
	if _, err := fmt.Fprintln(w, "# Generated by bnkctl. Do not edit by hand — run `bnkctl init` to update."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "# IBMCLOUD_API_KEY is NOT written here; it's passed via TF_VAR env var."); err != nil {
		return err
	}
	fmt.Fprintln(w)

	// IBM Cloud
	if ws.IBMCloud.Region != "" {
		fmt.Fprintf(w, "ibmcloud_cluster_region = %q\n", ws.IBMCloud.Region)
	}
	if ws.IBMCloud.ResourceGroup != "" {
		fmt.Fprintf(w, "ibmcloud_resource_group = %q\n", ws.IBMCloud.ResourceGroup)
	}

	// Cluster — branching on Create chooses which TF variable name carries
	// the cluster identity. The upstream module uses different names for
	// new (openshift_cluster_name) vs existing (roks_cluster_id_or_name).
	fmt.Fprintf(w, "create_roks_cluster = %v\n", ws.Cluster.Create)
	if ws.Cluster.Create {
		if ws.Cluster.Name != "" {
			fmt.Fprintf(w, "openshift_cluster_name = %q\n", ws.Cluster.Name)
		}
		if ws.Cluster.OpenShiftVersion != "" {
			fmt.Fprintf(w, "openshift_cluster_version = %q\n", ws.Cluster.OpenShiftVersion)
		}
		if ws.Cluster.WorkersPerZone > 0 {
			fmt.Fprintf(w, "roks_workers_per_zone = %d\n", ws.Cluster.WorkersPerZone)
		}
	} else {
		if ws.Cluster.Name != "" {
			fmt.Fprintf(w, "roks_cluster_id_or_name = %q\n", ws.Cluster.Name)
		}
	}

	// BNK
	if ws.BNK.CNEInstanceSize != "" {
		fmt.Fprintf(w, "cneinstance_deployment_size = %q\n", ws.BNK.CNEInstanceSize)
	}
	if ws.BNK.FARRepoURL != "" {
		fmt.Fprintf(w, "far_repo_url = %q\n", ws.BNK.FARRepoURL)
	}
	if ws.BNK.ManifestVersion != "" {
		fmt.Fprintf(w, "f5_bigip_k8s_manifest_version = %q\n", ws.BNK.ManifestVersion)
	}

	// Kubeconfig scratch dir. Overrides the module-internal /work/.bnk/...
	// default which only works inside the bnk runner image. Threaded to
	// each submodule by the root TF (v0.6.8+); older TF versions print a
	// "variable not declared" warning but otherwise behave the same.
	if kubeconfigDir != "" {
		fmt.Fprintf(w, "kubeconfig_dir = %q\n", kubeconfigDir)
	}

	return nil
}
